# Generated by Django 4.2 on 2023-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='mtype',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
