# Generated by Django 4.2 on 2023-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/NoneNo/img.jpg', upload_to='Images/'),
        ),
    ]
